### ISSUE TITLE
java.net.BindException: Cannot assign requested address

### ISSUE THREAD

**Issue by shengb** [epics-rip/ChannelFinderService#22]
It looks like CF/glassfish server sends a response back to CF client although ELK is still under processing previous request.
**gov.bnl.channelfinder.ElasticSearchClient.getNewClient(ElasticSearchClient.java:59)
gov.bnl.channelfinder.PropertiesResource.update(PropertiesResource.java:414)**

The detailed error message is as below.

[#|2018-01-29T16:08:25.590-0600|WARNING|glassfish 4.1|gov.bnl.channelfinder.PropertiesResource|_ThreadID=35;_ThreadName=http-listener-2(2);_TimeMillis=1517263705590;_LevelValue=900;|
  admin|properties/P2|PUT|ERROR|Internal Server Error|cause=None of the configured nodes are available: []|#]
 
[#|2018-01-29T16:08:25.610-0600|INFO|glassfish 4.1||_ThreadID=38;_ThreadName=http-listener-2(5);_TimeMillis=1517263705610;_LevelValue=800;|
  [Blaquesmith] loaded [], sites []|#]
 
[#|2018-01-29T16:08:25.618-0600|WARNING|glassfish 4.1||_ThreadID=38;_ThreadName=http-listener-2(5);_TimeMillis=1517263705618;_LevelValue=900;|
  [Blaquesmith] exception caught on transport layer [[id: 0x4f8ebe97]], closing connection
java.net.BindException: Cannot assign requested address
                at sun.nio.ch.Net.connect0(Native Method)
                at sun.nio.ch.Net.connect(Net.java:454)
                at sun.nio.ch.Net.connect(Net.java:446)
                at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
                at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:108)
                at org.elasticsearch.common.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:70)
                at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:574)
                at org.elasticsearch.common.netty.channel.Channels.connect(Channels.java:634)
                at org.elasticsearch.common.netty.channel.AbstractChannel.connect(AbstractChannel.java:216)
                at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
                at org.elasticsearch.common.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
                at org.elasticsearch.transport.netty.NettyTransport.connectToChannelsLight(NettyTransport.java:759)
                at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:727)
                at org.elasticsearch.transport.netty.NettyTransport.connectToNodeLight(NettyTransport.java:699)
                at org.elasticsearch.transport.TransportService.connectToNodeLight(TransportService.java:220)
                at org.elasticsearch.client.transport.TransportClientNodesService$SimpleNodeSampler.doSample(TransportClientNodesService.java:369)
                at org.elasticsearch.client.transport.TransportClientNodesService$NodeSampler.sample(TransportClientNodesService.java:315)
                at org.elasticsearch.client.transport.TransportClientNodesService.addTransportAddresses(TransportClientNodesService.java:174)
                at org.elasticsearch.client.transport.TransportClient.addTransportAddress(TransportClient.java:241)
                at gov.bnl.channelfinder.ElasticSearchClient.getNewClient(ElasticSearchClient.java:59)
                at gov.bnl.channelfinder.PropertiesResource.update(PropertiesResource.java:414)
                at sun.reflect.GeneratedMethodAccessor106.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
                at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
                at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
                at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
                at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
                at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
                at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
                at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
                at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:309)
                at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
                at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
                at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
                at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
                at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
                at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
                at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:292)
                at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1139)
                at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:460)
                at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
                at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334)
                at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
                at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:318)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
                at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
                at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
                at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
                at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:416)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283)
                at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
                at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
                at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
                at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
                at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
                at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
                at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283)
                at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200)
                at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132)
                at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111)
                at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
                at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:536)
                at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
                at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
                at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
                at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
                at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
                at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
                at java.lang.Thread.run(Thread.java:748)
|#]

**Comment by hjunkes** [comment]
I may have encountered the same problem. At least the message "None of the configured nodes are available"
Setting 
cluster.name: elasticsearch 
in /etc/elasticsearch/elasticsearch.yml solved the problem. 
I had chosen a different name (FELcf) before.

It would be nice if one could choose the name freely in the future.

**Comment by shroffk** [comment]
> It would be nice if one could choose the name freely in the future.

yes, this will be added as a configurable preference

**Comment by shroffk** [comment]
@shengb 
In your error it seems like the elastic client is failing to create the "transportNode"...the developers at elastic now discourage this method and instead encourage the use of their rest-client. I will add this to the next upgrade of channelfinder.

> java.net.BindException: Cannot assign requested address
