### ISSUE TITLE
Could not request resources

### ISSUE THREAD

**Issue by hjunkes** [epics-rip/ChannelFinderService#29]
Had to replace jackson-xxx jar's in glassfish/modules by version 2.5.1 ones.
(add jackson-module-jaxb-annotations-2.5.1.jar)
-rw-r--r-- 1 glassfish glassfishadm   39817 Feb  7  2015 jackson-annotations-2.5.1.jar
-rw-r--r-- 1 glassfish glassfishadm  229860 Feb  7  2015 jackson-core-2.5.1.jar
-rw-r--r-- 1 glassfish glassfishadm 1138921 Feb  7  2015 jackson-databind-2.5.1.jar
-rw-r--r-- 1 glassfish glassfishadm   32459 Feb  7  2015 jackson-module-jaxb-annotations-2.5.1.jar
-rw-r--r-- 1 glassfish glassfishadm   28723 Feb  7  2015 jackson-jaxrs-base-2.5.1.jar
-rw-r--r-- 1 glassfish glassfishadm   16692 Feb  7  2015 jackson-jaxrs-json-provider-2.5.1.jar

sudo rm jackson-annotations.jar 
sudo rm jackson-core.jar 
sudo rm jackson-databind.jar
sudo rm jackson-jaxrs-base.jar
sudo rm jackson-jaxrs-json-provider.jar

from maven2 repo
sudo wget http://central.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.5.1/jackson-module-jaxb-annotations-2.5.1.jar .
sudo wget http://central.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.5.1/jackson-annotations-2.5.1.jar
sudo wget http://central.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.5.1/jackson-core-2.5.1.jar
sudo wget http://central.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.5.1/jackson-databind-2.5.1.jar
sudo wget http://central.maven.org/maven2/com/fasterxml/jackson/jaxrs/jackson-jaxrs-base/2.5.1/jackson-jaxrs-base-2.5.1.jar
sudo wget http://central.maven.org/maven2/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.5.1/jackson-jaxrs-json-provider-2.5.1.jar

The cache must be deleted before glassfish is started again.
In /home/glassfish/glassfish/osgi
sudo rm -rf felix

**Comment by hjunkes** [comment]
in addition I had to rename 
jackson-core-2.5.1.jar to jackson-core.jar in modules.

Got
stopping glassfish from /home/glassfish/bin
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonFactory
	at com.sun.enterprise.admin.remote.reader.ProgressStatusDTOJsonProprietaryReader.<clinit>(ProgressStatusDTOJsonProprietaryReader.java:57)
	at com.sun.enterprise.admin.remote.reader.ProprietaryReaderFactory.<clinit>(ProprietaryReaderFactory.java:60)
	at com.sun.enterprise.admin.cli.AdminMain$2.run(AdminMain.java:272)
	at java.lang.Thread.run(Thread.java:745)
