### ISSUE TITLE
example/demo.py local variable 'f' referenced before assignment

### ISSUE THREAD

**Issue by mdavidsaver** [epics-rip/ChannelFinderService#30]
```py
PYTHONPATH=$PWD python example/demo.py 
[{u'owner': u'cf-update', u'name': u'elem_name', u'value': None}, {u'owner': u'cf-update', u'name': u's_position', u'value': None}, {u'owner': u'cf-update', u'name': u'time', u'value': None}, {u'owner': u'cf-update', u'name': u'girder', u'value': None}, {u'owner': u'cf-update', u'name': u'symmetry', u'value': None}, {u'owner': u'cf-update', u'name': u'hostName', u'value': None}, {u'owner': u'cf-update', u'name': u'dev_name', u'value': None}, {u'owner': u'cf-update', u'name': u'ioctest', u'value': None}, {u'owner': u'cf-update', u'name': u'system', u'value': None}, {u'owner': u'cf-update', u'name': u'iocName', u'value': None}, {u'owner': u'cf-update', u'name': u'iocid', u'value': None}, {u'owner': u'cf-update', u'name': u'ordinal', u'value': None}, {u'owner': u'cf-update', u'name': u'elem_type', u'value': None}, {u'owner': u'cf-update', u'name': u'pvStatus', u'value': None}, {u'owner': u'cf-update', u'name': u'iocidtest', u'value': None}, {u'owner': u'cf-update', u'name': u'cell', u'value': None}, {u'owner': u'cf-update', u'name': u'length', u'value': None}, {u'owner': u'cf-update', u'name': u'handle', u'value': None}]
Traceback (most recent call last):
  File "example/demo.py", line 178, in <module>
    channel_demo(cf)
  File "example/demo.py", line 115, in channel_demo
    f.close()
UnboundLocalError: local variable 'f' referenced before assignment
```

**Comment by mdavidsaver** [comment]
oops, wrong repo
